### ISSUE TITLE
Request format is invalid: Missing required soap:Body element

### ISSUE THREAD

**Issue by hasanmumin** [adamski/react-native-soap-request#1]
Hi,
I try to use your library but looks like it is deleting body before request.

request:

```
const soapRequest = new SoapRequest({
            security: {
                username: 'username',
                password: 'password'
            },
            requestURL: soapWebserviceURL
        });

        const xmlRequest = soapRequest.createRequest({
            'Get_Kategoriler': {
                attributes: {
                    'xmlns:soap': 'http://tempuri.org/'
                }
            }
        });

        const response = await soapRequest.sendRequest();

        console.log(response);
```

error (console) message:

`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>Server was unable to process request. ---&gt; Request format is invalid: Missing required soap:Body element.</faultstring><detail /></soap:Fault></soap:Body></soap:Envelope>`

**Comment by adamski** [comment]
Can you confirm this by posting the generated XML request? 
I.e. 
```js
console.log(xmlRequest);
```

Perhaps the format it is sending is not compatible with what your server is expecting?

**Comment by hasanmumin** [comment]
@adamski thank you for quick response. It is my bad. Thanks !
