### ISSUE TITLE
Error: undefined is not a constructor (evaluating 'new_reactNative.SoapRequest)

### ISSUE THREAD

**Issue by chandru8285** [adamski/react-native-soap-request#4]
Hi, I am new to the react-native library. I have the following issue when I copy the sample request into the sample file (App.js).

import React, {Component} from 'react';
import {SoapRequest, Platform, StyleSheet, Text, View} from 'react-native';

let soapWebserviceURL = 'http://127.0.0.1:8088/mockServiceSoapBinding';

const soapRequest = new SoapRequest({
  security: {
    username: 'username',
    password: 'password'
  },
  targetNamespace: 'http://soap.acme.com/2.0/soap-access-services',
  commonTypes: 'http://soap.acme.com/2.0/soap-common-types',
  requestURL: soapWebserviceURL
});

const xmlRequest = soapRequest.createRequest({
  'soap:ProductRegistrationRequest': {
    attributes: {
      'xmlns:soap': 'http://soap.acme.com/2.0/soap-access-services',
      'xmlns:cmn': 'http://soap.acme.com/2.0/soap-common-types'
    },
    'soap:productId': {
      'cmn:internalId': {
        'cmn:id': productId
      }
    },
    'soap:userId': {
      'cmn:internalId': {
        'cmn:id': userId
      }
    }
  }
});

const response = soapRequest.sendRequest();

console.log(response);

export default class App extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>{response}</Text>
      </View>
    );
  }
}

-------------
Error: 
undefined is not a constructor (evaluating 'new_reactNative.SoapRequest)

I don't know how to resolve this issue, can you help me to fix this issue?
 
![image](https://user-images.githubusercontent.com/48527286/54298832-7e9bfe80-45f4-11e9-8653-85d4f7aaff2d.png)

**Comment by adamski** [comment]
You are trying to import a third party library from 'react-native'. 

Replace
```
import {SoapRequest, Platform, StyleSheet, Text, View} from 'react-native';
```
with
```
import {Platform, StyleSheet, Text, View} from 'react-native';
import SoapRequest from 'react-native-soap-request';
```
